#ifndef _ZENO_SPEC_SRC_PARSING_LIMITS_H
#define _ZENO_SPEC_SRC_PARSING_LIMITS_H

#define MAX_CHARACTERS_PER_FILE 4194303
#define MAX_LINES_PER_FILE 1048575
#define MAX_CHARACTERS_PER_LINE 4095

#endif
